require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlignsController do

  # This should return the minimal set of attributes required to create a valid
  # Align. As you add validations to Align, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlignsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aligns as @aligns" do
      align = Align.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aligns).should eq([align])
    end
  end

  describe "GET show" do
    it "assigns the requested align as @align" do
      align = Align.create! valid_attributes
      get :show, {:id => align.to_param}, valid_session
      assigns(:align).should eq(align)
    end
  end

  describe "GET new" do
    it "assigns a new align as @align" do
      get :new, {}, valid_session
      assigns(:align).should be_a_new(Align)
    end
  end

  describe "GET edit" do
    it "assigns the requested align as @align" do
      align = Align.create! valid_attributes
      get :edit, {:id => align.to_param}, valid_session
      assigns(:align).should eq(align)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Align" do
        expect {
          post :create, {:align => valid_attributes}, valid_session
        }.to change(Align, :count).by(1)
      end

      it "assigns a newly created align as @align" do
        post :create, {:align => valid_attributes}, valid_session
        assigns(:align).should be_a(Align)
        assigns(:align).should be_persisted
      end

      it "redirects to the created align" do
        post :create, {:align => valid_attributes}, valid_session
        response.should redirect_to(Align.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved align as @align" do
        # Trigger the behavior that occurs when invalid params are submitted
        Align.any_instance.stub(:save).and_return(false)
        post :create, {:align => {  }}, valid_session
        assigns(:align).should be_a_new(Align)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Align.any_instance.stub(:save).and_return(false)
        post :create, {:align => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested align" do
        align = Align.create! valid_attributes
        # Assuming there are no other aligns in the database, this
        # specifies that the Align created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Align.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => align.to_param, :align => { "these" => "params" }}, valid_session
      end

      it "assigns the requested align as @align" do
        align = Align.create! valid_attributes
        put :update, {:id => align.to_param, :align => valid_attributes}, valid_session
        assigns(:align).should eq(align)
      end

      it "redirects to the align" do
        align = Align.create! valid_attributes
        put :update, {:id => align.to_param, :align => valid_attributes}, valid_session
        response.should redirect_to(align)
      end
    end

    describe "with invalid params" do
      it "assigns the align as @align" do
        align = Align.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Align.any_instance.stub(:save).and_return(false)
        put :update, {:id => align.to_param, :align => {  }}, valid_session
        assigns(:align).should eq(align)
      end

      it "re-renders the 'edit' template" do
        align = Align.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Align.any_instance.stub(:save).and_return(false)
        put :update, {:id => align.to_param, :align => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested align" do
      align = Align.create! valid_attributes
      expect {
        delete :destroy, {:id => align.to_param}, valid_session
      }.to change(Align, :count).by(-1)
    end

    it "redirects to the aligns list" do
      align = Align.create! valid_attributes
      delete :destroy, {:id => align.to_param}, valid_session
      response.should redirect_to(aligns_url)
    end
  end

end
