require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnnoncmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Annoncment. As you add validations to Annoncment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnnoncmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all annoncments as @annoncments" do
      annoncment = Annoncment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:annoncments).should eq([annoncment])
    end
  end

  describe "GET show" do
    it "assigns the requested annoncment as @annoncment" do
      annoncment = Annoncment.create! valid_attributes
      get :show, {:id => annoncment.to_param}, valid_session
      assigns(:annoncment).should eq(annoncment)
    end
  end

  describe "GET new" do
    it "assigns a new annoncment as @annoncment" do
      get :new, {}, valid_session
      assigns(:annoncment).should be_a_new(Annoncment)
    end
  end

  describe "GET edit" do
    it "assigns the requested annoncment as @annoncment" do
      annoncment = Annoncment.create! valid_attributes
      get :edit, {:id => annoncment.to_param}, valid_session
      assigns(:annoncment).should eq(annoncment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Annoncment" do
        expect {
          post :create, {:annoncment => valid_attributes}, valid_session
        }.to change(Annoncment, :count).by(1)
      end

      it "assigns a newly created annoncment as @annoncment" do
        post :create, {:annoncment => valid_attributes}, valid_session
        assigns(:annoncment).should be_a(Annoncment)
        assigns(:annoncment).should be_persisted
      end

      it "redirects to the created annoncment" do
        post :create, {:annoncment => valid_attributes}, valid_session
        response.should redirect_to(Annoncment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved annoncment as @annoncment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Annoncment.any_instance.stub(:save).and_return(false)
        post :create, {:annoncment => {  }}, valid_session
        assigns(:annoncment).should be_a_new(Annoncment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Annoncment.any_instance.stub(:save).and_return(false)
        post :create, {:annoncment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested annoncment" do
        annoncment = Annoncment.create! valid_attributes
        # Assuming there are no other annoncments in the database, this
        # specifies that the Annoncment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Annoncment.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => annoncment.to_param, :annoncment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested annoncment as @annoncment" do
        annoncment = Annoncment.create! valid_attributes
        put :update, {:id => annoncment.to_param, :annoncment => valid_attributes}, valid_session
        assigns(:annoncment).should eq(annoncment)
      end

      it "redirects to the annoncment" do
        annoncment = Annoncment.create! valid_attributes
        put :update, {:id => annoncment.to_param, :annoncment => valid_attributes}, valid_session
        response.should redirect_to(annoncment)
      end
    end

    describe "with invalid params" do
      it "assigns the annoncment as @annoncment" do
        annoncment = Annoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Annoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => annoncment.to_param, :annoncment => {  }}, valid_session
        assigns(:annoncment).should eq(annoncment)
      end

      it "re-renders the 'edit' template" do
        annoncment = Annoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Annoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => annoncment.to_param, :annoncment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested annoncment" do
      annoncment = Annoncment.create! valid_attributes
      expect {
        delete :destroy, {:id => annoncment.to_param}, valid_session
      }.to change(Annoncment, :count).by(-1)
    end

    it "redirects to the annoncments list" do
      annoncment = Annoncment.create! valid_attributes
      delete :destroy, {:id => annoncment.to_param}, valid_session
      response.should redirect_to(annoncments_url)
    end
  end

end
