require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BackgroundAnnoncmentsController do

  # This should return the minimal set of attributes required to create a valid
  # BackgroundAnnoncment. As you add validations to BackgroundAnnoncment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BackgroundAnnoncmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all background_annoncments as @background_annoncments" do
      background_annoncment = BackgroundAnnoncment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:background_annoncments).should eq([background_annoncment])
    end
  end

  describe "GET show" do
    it "assigns the requested background_annoncment as @background_annoncment" do
      background_annoncment = BackgroundAnnoncment.create! valid_attributes
      get :show, {:id => background_annoncment.to_param}, valid_session
      assigns(:background_annoncment).should eq(background_annoncment)
    end
  end

  describe "GET new" do
    it "assigns a new background_annoncment as @background_annoncment" do
      get :new, {}, valid_session
      assigns(:background_annoncment).should be_a_new(BackgroundAnnoncment)
    end
  end

  describe "GET edit" do
    it "assigns the requested background_annoncment as @background_annoncment" do
      background_annoncment = BackgroundAnnoncment.create! valid_attributes
      get :edit, {:id => background_annoncment.to_param}, valid_session
      assigns(:background_annoncment).should eq(background_annoncment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BackgroundAnnoncment" do
        expect {
          post :create, {:background_annoncment => valid_attributes}, valid_session
        }.to change(BackgroundAnnoncment, :count).by(1)
      end

      it "assigns a newly created background_annoncment as @background_annoncment" do
        post :create, {:background_annoncment => valid_attributes}, valid_session
        assigns(:background_annoncment).should be_a(BackgroundAnnoncment)
        assigns(:background_annoncment).should be_persisted
      end

      it "redirects to the created background_annoncment" do
        post :create, {:background_annoncment => valid_attributes}, valid_session
        response.should redirect_to(BackgroundAnnoncment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved background_annoncment as @background_annoncment" do
        # Trigger the behavior that occurs when invalid params are submitted
        BackgroundAnnoncment.any_instance.stub(:save).and_return(false)
        post :create, {:background_annoncment => {  }}, valid_session
        assigns(:background_annoncment).should be_a_new(BackgroundAnnoncment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BackgroundAnnoncment.any_instance.stub(:save).and_return(false)
        post :create, {:background_annoncment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested background_annoncment" do
        background_annoncment = BackgroundAnnoncment.create! valid_attributes
        # Assuming there are no other background_annoncments in the database, this
        # specifies that the BackgroundAnnoncment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BackgroundAnnoncment.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => background_annoncment.to_param, :background_annoncment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested background_annoncment as @background_annoncment" do
        background_annoncment = BackgroundAnnoncment.create! valid_attributes
        put :update, {:id => background_annoncment.to_param, :background_annoncment => valid_attributes}, valid_session
        assigns(:background_annoncment).should eq(background_annoncment)
      end

      it "redirects to the background_annoncment" do
        background_annoncment = BackgroundAnnoncment.create! valid_attributes
        put :update, {:id => background_annoncment.to_param, :background_annoncment => valid_attributes}, valid_session
        response.should redirect_to(background_annoncment)
      end
    end

    describe "with invalid params" do
      it "assigns the background_annoncment as @background_annoncment" do
        background_annoncment = BackgroundAnnoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BackgroundAnnoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => background_annoncment.to_param, :background_annoncment => {  }}, valid_session
        assigns(:background_annoncment).should eq(background_annoncment)
      end

      it "re-renders the 'edit' template" do
        background_annoncment = BackgroundAnnoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BackgroundAnnoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => background_annoncment.to_param, :background_annoncment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested background_annoncment" do
      background_annoncment = BackgroundAnnoncment.create! valid_attributes
      expect {
        delete :destroy, {:id => background_annoncment.to_param}, valid_session
      }.to change(BackgroundAnnoncment, :count).by(-1)
    end

    it "redirects to the background_annoncments list" do
      background_annoncment = BackgroundAnnoncment.create! valid_attributes
      delete :destroy, {:id => background_annoncment.to_param}, valid_session
      response.should redirect_to(background_annoncments_url)
    end
  end

end
