require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContentsOrAnnoncmentsController do

  # This should return the minimal set of attributes required to create a valid
  # ContentsOrAnnoncment. As you add validations to ContentsOrAnnoncment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContentsOrAnnoncmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contents_or_annoncments as @contents_or_annoncments" do
      contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contents_or_annoncments).should eq([contents_or_annoncment])
    end
  end

  describe "GET show" do
    it "assigns the requested contents_or_annoncment as @contents_or_annoncment" do
      contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
      get :show, {:id => contents_or_annoncment.to_param}, valid_session
      assigns(:contents_or_annoncment).should eq(contents_or_annoncment)
    end
  end

  describe "GET new" do
    it "assigns a new contents_or_annoncment as @contents_or_annoncment" do
      get :new, {}, valid_session
      assigns(:contents_or_annoncment).should be_a_new(ContentsOrAnnoncment)
    end
  end

  describe "GET edit" do
    it "assigns the requested contents_or_annoncment as @contents_or_annoncment" do
      contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
      get :edit, {:id => contents_or_annoncment.to_param}, valid_session
      assigns(:contents_or_annoncment).should eq(contents_or_annoncment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContentsOrAnnoncment" do
        expect {
          post :create, {:contents_or_annoncment => valid_attributes}, valid_session
        }.to change(ContentsOrAnnoncment, :count).by(1)
      end

      it "assigns a newly created contents_or_annoncment as @contents_or_annoncment" do
        post :create, {:contents_or_annoncment => valid_attributes}, valid_session
        assigns(:contents_or_annoncment).should be_a(ContentsOrAnnoncment)
        assigns(:contents_or_annoncment).should be_persisted
      end

      it "redirects to the created contents_or_annoncment" do
        post :create, {:contents_or_annoncment => valid_attributes}, valid_session
        response.should redirect_to(ContentsOrAnnoncment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contents_or_annoncment as @contents_or_annoncment" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentsOrAnnoncment.any_instance.stub(:save).and_return(false)
        post :create, {:contents_or_annoncment => {  }}, valid_session
        assigns(:contents_or_annoncment).should be_a_new(ContentsOrAnnoncment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContentsOrAnnoncment.any_instance.stub(:save).and_return(false)
        post :create, {:contents_or_annoncment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contents_or_annoncment" do
        contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
        # Assuming there are no other contents_or_annoncments in the database, this
        # specifies that the ContentsOrAnnoncment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContentsOrAnnoncment.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => contents_or_annoncment.to_param, :contents_or_annoncment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested contents_or_annoncment as @contents_or_annoncment" do
        contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
        put :update, {:id => contents_or_annoncment.to_param, :contents_or_annoncment => valid_attributes}, valid_session
        assigns(:contents_or_annoncment).should eq(contents_or_annoncment)
      end

      it "redirects to the contents_or_annoncment" do
        contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
        put :update, {:id => contents_or_annoncment.to_param, :contents_or_annoncment => valid_attributes}, valid_session
        response.should redirect_to(contents_or_annoncment)
      end
    end

    describe "with invalid params" do
      it "assigns the contents_or_annoncment as @contents_or_annoncment" do
        contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentsOrAnnoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => contents_or_annoncment.to_param, :contents_or_annoncment => {  }}, valid_session
        assigns(:contents_or_annoncment).should eq(contents_or_annoncment)
      end

      it "re-renders the 'edit' template" do
        contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContentsOrAnnoncment.any_instance.stub(:save).and_return(false)
        put :update, {:id => contents_or_annoncment.to_param, :contents_or_annoncment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contents_or_annoncment" do
      contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
      expect {
        delete :destroy, {:id => contents_or_annoncment.to_param}, valid_session
      }.to change(ContentsOrAnnoncment, :count).by(-1)
    end

    it "redirects to the contents_or_annoncments list" do
      contents_or_annoncment = ContentsOrAnnoncment.create! valid_attributes
      delete :destroy, {:id => contents_or_annoncment.to_param}, valid_session
      response.should redirect_to(contents_or_annoncments_url)
    end
  end

end
