require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FooterBackgroundsController do

  # This should return the minimal set of attributes required to create a valid
  # FooterBackground. As you add validations to FooterBackground, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FooterBackgroundsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all footer_backgrounds as @footer_backgrounds" do
      footer_background = FooterBackground.create! valid_attributes
      get :index, {}, valid_session
      assigns(:footer_backgrounds).should eq([footer_background])
    end
  end

  describe "GET show" do
    it "assigns the requested footer_background as @footer_background" do
      footer_background = FooterBackground.create! valid_attributes
      get :show, {:id => footer_background.to_param}, valid_session
      assigns(:footer_background).should eq(footer_background)
    end
  end

  describe "GET new" do
    it "assigns a new footer_background as @footer_background" do
      get :new, {}, valid_session
      assigns(:footer_background).should be_a_new(FooterBackground)
    end
  end

  describe "GET edit" do
    it "assigns the requested footer_background as @footer_background" do
      footer_background = FooterBackground.create! valid_attributes
      get :edit, {:id => footer_background.to_param}, valid_session
      assigns(:footer_background).should eq(footer_background)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FooterBackground" do
        expect {
          post :create, {:footer_background => valid_attributes}, valid_session
        }.to change(FooterBackground, :count).by(1)
      end

      it "assigns a newly created footer_background as @footer_background" do
        post :create, {:footer_background => valid_attributes}, valid_session
        assigns(:footer_background).should be_a(FooterBackground)
        assigns(:footer_background).should be_persisted
      end

      it "redirects to the created footer_background" do
        post :create, {:footer_background => valid_attributes}, valid_session
        response.should redirect_to(FooterBackground.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved footer_background as @footer_background" do
        # Trigger the behavior that occurs when invalid params are submitted
        FooterBackground.any_instance.stub(:save).and_return(false)
        post :create, {:footer_background => {  }}, valid_session
        assigns(:footer_background).should be_a_new(FooterBackground)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FooterBackground.any_instance.stub(:save).and_return(false)
        post :create, {:footer_background => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested footer_background" do
        footer_background = FooterBackground.create! valid_attributes
        # Assuming there are no other footer_backgrounds in the database, this
        # specifies that the FooterBackground created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FooterBackground.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => footer_background.to_param, :footer_background => { "these" => "params" }}, valid_session
      end

      it "assigns the requested footer_background as @footer_background" do
        footer_background = FooterBackground.create! valid_attributes
        put :update, {:id => footer_background.to_param, :footer_background => valid_attributes}, valid_session
        assigns(:footer_background).should eq(footer_background)
      end

      it "redirects to the footer_background" do
        footer_background = FooterBackground.create! valid_attributes
        put :update, {:id => footer_background.to_param, :footer_background => valid_attributes}, valid_session
        response.should redirect_to(footer_background)
      end
    end

    describe "with invalid params" do
      it "assigns the footer_background as @footer_background" do
        footer_background = FooterBackground.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FooterBackground.any_instance.stub(:save).and_return(false)
        put :update, {:id => footer_background.to_param, :footer_background => {  }}, valid_session
        assigns(:footer_background).should eq(footer_background)
      end

      it "re-renders the 'edit' template" do
        footer_background = FooterBackground.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FooterBackground.any_instance.stub(:save).and_return(false)
        put :update, {:id => footer_background.to_param, :footer_background => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested footer_background" do
      footer_background = FooterBackground.create! valid_attributes
      expect {
        delete :destroy, {:id => footer_background.to_param}, valid_session
      }.to change(FooterBackground, :count).by(-1)
    end

    it "redirects to the footer_backgrounds list" do
      footer_background = FooterBackground.create! valid_attributes
      delete :destroy, {:id => footer_background.to_param}, valid_session
      response.should redirect_to(footer_backgrounds_url)
    end
  end

end
