require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FootersController do

  # This should return the minimal set of attributes required to create a valid
  # Footer. As you add validations to Footer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FootersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all footers as @footers" do
      footer = Footer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:footers).should eq([footer])
    end
  end

  describe "GET show" do
    it "assigns the requested footer as @footer" do
      footer = Footer.create! valid_attributes
      get :show, {:id => footer.to_param}, valid_session
      assigns(:footer).should eq(footer)
    end
  end

  describe "GET new" do
    it "assigns a new footer as @footer" do
      get :new, {}, valid_session
      assigns(:footer).should be_a_new(Footer)
    end
  end

  describe "GET edit" do
    it "assigns the requested footer as @footer" do
      footer = Footer.create! valid_attributes
      get :edit, {:id => footer.to_param}, valid_session
      assigns(:footer).should eq(footer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Footer" do
        expect {
          post :create, {:footer => valid_attributes}, valid_session
        }.to change(Footer, :count).by(1)
      end

      it "assigns a newly created footer as @footer" do
        post :create, {:footer => valid_attributes}, valid_session
        assigns(:footer).should be_a(Footer)
        assigns(:footer).should be_persisted
      end

      it "redirects to the created footer" do
        post :create, {:footer => valid_attributes}, valid_session
        response.should redirect_to(Footer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved footer as @footer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Footer.any_instance.stub(:save).and_return(false)
        post :create, {:footer => {  }}, valid_session
        assigns(:footer).should be_a_new(Footer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Footer.any_instance.stub(:save).and_return(false)
        post :create, {:footer => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested footer" do
        footer = Footer.create! valid_attributes
        # Assuming there are no other footers in the database, this
        # specifies that the Footer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Footer.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => footer.to_param, :footer => { "these" => "params" }}, valid_session
      end

      it "assigns the requested footer as @footer" do
        footer = Footer.create! valid_attributes
        put :update, {:id => footer.to_param, :footer => valid_attributes}, valid_session
        assigns(:footer).should eq(footer)
      end

      it "redirects to the footer" do
        footer = Footer.create! valid_attributes
        put :update, {:id => footer.to_param, :footer => valid_attributes}, valid_session
        response.should redirect_to(footer)
      end
    end

    describe "with invalid params" do
      it "assigns the footer as @footer" do
        footer = Footer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Footer.any_instance.stub(:save).and_return(false)
        put :update, {:id => footer.to_param, :footer => {  }}, valid_session
        assigns(:footer).should eq(footer)
      end

      it "re-renders the 'edit' template" do
        footer = Footer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Footer.any_instance.stub(:save).and_return(false)
        put :update, {:id => footer.to_param, :footer => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested footer" do
      footer = Footer.create! valid_attributes
      expect {
        delete :destroy, {:id => footer.to_param}, valid_session
      }.to change(Footer, :count).by(-1)
    end

    it "redirects to the footers list" do
      footer = Footer.create! valid_attributes
      delete :destroy, {:id => footer.to_param}, valid_session
      response.should redirect_to(footers_url)
    end
  end

end
