require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GaleryPhotosController do

  # This should return the minimal set of attributes required to create a valid
  # GaleryPhoto. As you add validations to GaleryPhoto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GaleryPhotosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all galery_photos as @galery_photos" do
      galery_photo = GaleryPhoto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:galery_photos).should eq([galery_photo])
    end
  end

  describe "GET show" do
    it "assigns the requested galery_photo as @galery_photo" do
      galery_photo = GaleryPhoto.create! valid_attributes
      get :show, {:id => galery_photo.to_param}, valid_session
      assigns(:galery_photo).should eq(galery_photo)
    end
  end

  describe "GET new" do
    it "assigns a new galery_photo as @galery_photo" do
      get :new, {}, valid_session
      assigns(:galery_photo).should be_a_new(GaleryPhoto)
    end
  end

  describe "GET edit" do
    it "assigns the requested galery_photo as @galery_photo" do
      galery_photo = GaleryPhoto.create! valid_attributes
      get :edit, {:id => galery_photo.to_param}, valid_session
      assigns(:galery_photo).should eq(galery_photo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GaleryPhoto" do
        expect {
          post :create, {:galery_photo => valid_attributes}, valid_session
        }.to change(GaleryPhoto, :count).by(1)
      end

      it "assigns a newly created galery_photo as @galery_photo" do
        post :create, {:galery_photo => valid_attributes}, valid_session
        assigns(:galery_photo).should be_a(GaleryPhoto)
        assigns(:galery_photo).should be_persisted
      end

      it "redirects to the created galery_photo" do
        post :create, {:galery_photo => valid_attributes}, valid_session
        response.should redirect_to(GaleryPhoto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved galery_photo as @galery_photo" do
        # Trigger the behavior that occurs when invalid params are submitted
        GaleryPhoto.any_instance.stub(:save).and_return(false)
        post :create, {:galery_photo => {  }}, valid_session
        assigns(:galery_photo).should be_a_new(GaleryPhoto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GaleryPhoto.any_instance.stub(:save).and_return(false)
        post :create, {:galery_photo => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested galery_photo" do
        galery_photo = GaleryPhoto.create! valid_attributes
        # Assuming there are no other galery_photos in the database, this
        # specifies that the GaleryPhoto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GaleryPhoto.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => galery_photo.to_param, :galery_photo => { "these" => "params" }}, valid_session
      end

      it "assigns the requested galery_photo as @galery_photo" do
        galery_photo = GaleryPhoto.create! valid_attributes
        put :update, {:id => galery_photo.to_param, :galery_photo => valid_attributes}, valid_session
        assigns(:galery_photo).should eq(galery_photo)
      end

      it "redirects to the galery_photo" do
        galery_photo = GaleryPhoto.create! valid_attributes
        put :update, {:id => galery_photo.to_param, :galery_photo => valid_attributes}, valid_session
        response.should redirect_to(galery_photo)
      end
    end

    describe "with invalid params" do
      it "assigns the galery_photo as @galery_photo" do
        galery_photo = GaleryPhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GaleryPhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => galery_photo.to_param, :galery_photo => {  }}, valid_session
        assigns(:galery_photo).should eq(galery_photo)
      end

      it "re-renders the 'edit' template" do
        galery_photo = GaleryPhoto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GaleryPhoto.any_instance.stub(:save).and_return(false)
        put :update, {:id => galery_photo.to_param, :galery_photo => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested galery_photo" do
      galery_photo = GaleryPhoto.create! valid_attributes
      expect {
        delete :destroy, {:id => galery_photo.to_param}, valid_session
      }.to change(GaleryPhoto, :count).by(-1)
    end

    it "redirects to the galery_photos list" do
      galery_photo = GaleryPhoto.create! valid_attributes
      delete :destroy, {:id => galery_photo.to_param}, valid_session
      response.should redirect_to(galery_photos_url)
    end
  end

end
