require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HomepageSubmenusController do

  # This should return the minimal set of attributes required to create a valid
  # HomepageSubmenu. As you add validations to HomepageSubmenu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HomepageSubmenusController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all homepage_submenus as @homepage_submenus" do
      homepage_submenu = HomepageSubmenu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:homepage_submenus).should eq([homepage_submenu])
    end
  end

  describe "GET show" do
    it "assigns the requested homepage_submenu as @homepage_submenu" do
      homepage_submenu = HomepageSubmenu.create! valid_attributes
      get :show, {:id => homepage_submenu.to_param}, valid_session
      assigns(:homepage_submenu).should eq(homepage_submenu)
    end
  end

  describe "GET new" do
    it "assigns a new homepage_submenu as @homepage_submenu" do
      get :new, {}, valid_session
      assigns(:homepage_submenu).should be_a_new(HomepageSubmenu)
    end
  end

  describe "GET edit" do
    it "assigns the requested homepage_submenu as @homepage_submenu" do
      homepage_submenu = HomepageSubmenu.create! valid_attributes
      get :edit, {:id => homepage_submenu.to_param}, valid_session
      assigns(:homepage_submenu).should eq(homepage_submenu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HomepageSubmenu" do
        expect {
          post :create, {:homepage_submenu => valid_attributes}, valid_session
        }.to change(HomepageSubmenu, :count).by(1)
      end

      it "assigns a newly created homepage_submenu as @homepage_submenu" do
        post :create, {:homepage_submenu => valid_attributes}, valid_session
        assigns(:homepage_submenu).should be_a(HomepageSubmenu)
        assigns(:homepage_submenu).should be_persisted
      end

      it "redirects to the created homepage_submenu" do
        post :create, {:homepage_submenu => valid_attributes}, valid_session
        response.should redirect_to(HomepageSubmenu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved homepage_submenu as @homepage_submenu" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomepageSubmenu.any_instance.stub(:save).and_return(false)
        post :create, {:homepage_submenu => {  }}, valid_session
        assigns(:homepage_submenu).should be_a_new(HomepageSubmenu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomepageSubmenu.any_instance.stub(:save).and_return(false)
        post :create, {:homepage_submenu => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested homepage_submenu" do
        homepage_submenu = HomepageSubmenu.create! valid_attributes
        # Assuming there are no other homepage_submenus in the database, this
        # specifies that the HomepageSubmenu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HomepageSubmenu.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => homepage_submenu.to_param, :homepage_submenu => { "these" => "params" }}, valid_session
      end

      it "assigns the requested homepage_submenu as @homepage_submenu" do
        homepage_submenu = HomepageSubmenu.create! valid_attributes
        put :update, {:id => homepage_submenu.to_param, :homepage_submenu => valid_attributes}, valid_session
        assigns(:homepage_submenu).should eq(homepage_submenu)
      end

      it "redirects to the homepage_submenu" do
        homepage_submenu = HomepageSubmenu.create! valid_attributes
        put :update, {:id => homepage_submenu.to_param, :homepage_submenu => valid_attributes}, valid_session
        response.should redirect_to(homepage_submenu)
      end
    end

    describe "with invalid params" do
      it "assigns the homepage_submenu as @homepage_submenu" do
        homepage_submenu = HomepageSubmenu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomepageSubmenu.any_instance.stub(:save).and_return(false)
        put :update, {:id => homepage_submenu.to_param, :homepage_submenu => {  }}, valid_session
        assigns(:homepage_submenu).should eq(homepage_submenu)
      end

      it "re-renders the 'edit' template" do
        homepage_submenu = HomepageSubmenu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomepageSubmenu.any_instance.stub(:save).and_return(false)
        put :update, {:id => homepage_submenu.to_param, :homepage_submenu => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested homepage_submenu" do
      homepage_submenu = HomepageSubmenu.create! valid_attributes
      expect {
        delete :destroy, {:id => homepage_submenu.to_param}, valid_session
      }.to change(HomepageSubmenu, :count).by(-1)
    end

    it "redirects to the homepage_submenus list" do
      homepage_submenu = HomepageSubmenu.create! valid_attributes
      delete :destroy, {:id => homepage_submenu.to_param}, valid_session
      response.should redirect_to(homepage_submenus_url)
    end
  end

end
